feat: support regexp as function
vojtajina/grunt-bump pull request #189
Opened 2016-07-13 15:13 UTC by ctjhoa

This is useful if you want to reuse options in the RegExp.
eg:
```js
grunt.initConfig({
  bump: {
    options: {
      regExp: function() {
        return new RegExp('' + grunt.task.current.options.prereleaseName + '');
      }
    }
  }
});
```

2016-09-08 19:24 UTC, eddiemonge commented
Can you give an example of how this is useful?

2016-09-12 15:16 UTC, ctjhoa commented
Take a look https://github.com/csnover/TraceKit/pull/64/commits/1e6703b5f3543e8a9b268648bf22de146e07ba5c

I was forced to create a new `gruntBumpPrereleaseName` to remove the dot which cause issue #190 

With this PR you can reuse directly grunt current task variables.

2018-04-10 16:01 UTC, eddiemonge requested changes

2018-04-10 16:01 UTC, eddiemonge commented on tasks/bump.js
> +    var VERSION_REGEXP = (typeof(opts.regExp) == 'function') ? opts.regExp() : opts.regExp || new RegExp(
if this is a function, then it should pass `opts.prereleaseName` so the function can use it

2018-10-28 13:35 UTC, ctjhoa commented
@eddiemonge Updated. Sorry for the late reply I didn't notice your request change.

2018-11-14 00:13 UTC, eddiemonge commented on tasks/bump.js
> +    var VERSION_REGEXP = (typeof(opts.regExp) == 'function') ? opts.regExp(opts.prereleaseName) : opts.regExp || new RegExp(
`typeof opts.regExp === 'function'`

2018-11-14 00:17 UTC, eddiemonge requested changes
1 last change then I can merge it @ctjhoa

2018-11-15 18:11 UTC, ctjhoa commented
@eddiemonge done

2018-11-15 20:50 UTC, eddiemonge approved these changes

2018-11-15 20:50 UTC, merged