feat: pull from remote before push
vojtajina/grunt-bump pull request #194
Opened 2016-12-07 16:13 UTC by mojoaxel

added option `pull`
added option `pullAutoCommit`

fixes #193

2016-12-13 17:26 UTC, eddiemonge commented
on hold. discussion on going in issue

2016-12-13 17:27 UTC, eddiemonge requested changes

2016-12-13 17:27 UTC, eddiemonge commented on README.md
> +Set `options.pullAutoCommit` to true, if you want git to perform a merge with a auto-generated message.
shouldn't this be true then?

2018-04-10 18:08 UTC, mojoaxel commented
see discussion in #193

2018-04-10 18:08 UTC, closed without merging