feat: add option cwd
vojtajina/grunt-bump pull request #199
Opened 2017-01-18 22:14 UTC by mojoaxel

2017-01-20 17:21 UTC, eddiemonge requested changes

2017-01-20 17:21 UTC, eddiemonge commented on package.json
> +    "grunt-auto-release": "^0.0.7",
can you move these to a new PR?

2017-01-20 17:21 UTC, eddiemonge commented on tasks/bump.js
> +      grunt.fatal('The in "cwd" defined directory does not exist');
`The "cwd" requested does not exist`

2017-01-20 17:21 UTC, eddiemonge commented on tasks/bump.js
> +    grunt.verbose.writeln('Changing working directory: ' + opts.cwd);
Only show this if cwd `!== '.'`

2017-01-20 17:21 UTC, eddiemonge commented on tasks/bump.js
> +    grunt.file.setBase(opts.cwd);
I don't know if this sets this just for this task or all tasks so maybe store the current base and then restore it after the tasks have run.

2017-01-21 20:17 UTC, mojoaxel commented on package.json
> +    "grunt-auto-release": "^0.0.7",
yeah. ok. it's cleaner that way.

2017-01-21 20:18 UTC, mojoaxel commented on tasks/bump.js
> +      grunt.fatal('The in "cwd" defined directory does not exist');
:+1:

2017-01-21 20:20 UTC, mojoaxel commented on tasks/bump.js
> +    grunt.verbose.writeln('Changing working directory: ' + opts.cwd);
I think it doesn't hurt if the current working directory is shown to the user. This is only in `--verbose` mode. But I'm also ok, with the change.

2017-01-21 20:21 UTC, mojoaxel commented on tasks/bump.js
> +    grunt.file.setBase(opts.cwd);
Good point! I haven't tested it with multiple tasks. I better change it back!

2017-01-23 20:19 UTC, eddiemonge commented on tasks/bump.js
> +          grunt.file.setBase(originalCwd);
wont this mess up the file list for every exec after the first? Should the original changeBase go in the runIf?

2018-11-15 20:51 UTC, eddiemonge commented
Closing due to inactivity

2018-11-15 20:51 UTC, closed without merging